import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useForm } from 'react-hook-form'
import styles from '../styles/Home.module.css'
import { withApollo } from '../lib/withApollo'

function Home() {
  const router = useRouter()
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm()

  const onSubmit = ({ name }) => {
    void router.push({
      pathname: '/grid',
      query: {
        name,
      },
    })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>rt-grid-example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{`Welcome to "rt-grid"`}</h1>

        <p className={styles.description}>실시간 그리드 수정에 참여하세요.</p>
        <form onSubmit={handleSubmit(onSubmit)}>
          <label>
            이름: <input {...register('name', { required: true })} />
          </label>
          <button type="submit">참여</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default withApollo()(Home)
